# Generated by Django 4.2.30 on 2026-09-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.CharField(max_length=50, unique=True, verbose_name='ID Contrato')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('establecimiento', models.CharField(max_length=150, verbose_name='Establecimiento / Campo')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('arrendador', models.CharField(max_length=150, verbose_name='Arrendador / Propietario')),
                ('arrendatario', models.CharField(default='Administración Rural', max_length=150, verbose_name='Arrendatario')),
                ('campana', models.CharField(default='2024/2025', max_length=50, verbose_name='Campaña')),
                ('superficie_ha', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Superficie (Ha)')),
                ('cultivo_pactado', models.CharField(default='Soja', max_length=50, verbose_name='Cultivo Pactado')),
                ('modalidad', models.CharField(default='12.0 qq/ha', max_length=50, verbose_name='Modalidad')),
                ('kg_pactados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Kg Pactados')),
                ('kg_pagados', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Kg Pagados')),
                ('saldo_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo en Kg')),
                ('precio_tn', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Tn (USD)')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total USD')),
                ('pagado_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pagado USD')),
                ('saldo_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo USD')),
                ('factura_recibida', models.BooleanField(default=False, verbose_name='¿Factura Recibida?')),
                ('estado', models.CharField(default='ACTIVO', max_length=50, verbose_name='Estado')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Contrato de Arrendamiento',
                'verbose_name_plural': 'Contratos de Arrendamiento',
                'ordering': ['establecimiento'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('dolar_bna_venta', models.DecimalField(decimal_places=2, default=1535.0, max_digits=10, verbose_name='Dólar BNA Venta')),
                ('dolar_bna_compra', models.DecimalField(decimal_places=2, default=1485.0, max_digits=10, verbose_name='Dólar BNA Compra')),
                ('dolar_bna_mayorista', models.DecimalField(decimal_places=2, default=1514.0, max_digits=10, verbose_name='Dólar BNA Mayorista')),
                ('rosario_soja', models.DecimalField(decimal_places=2, default=342000.0, max_digits=12, verbose_name='Soja Rosario ($/Tn)')),
                ('rosario_maiz', models.DecimalField(decimal_places=2, default=198000.0, max_digits=12, verbose_name='Maíz Rosario ($/Tn)')),
                ('rosario_trigo', models.DecimalField(decimal_places=2, default=245000.0, max_digits=12, verbose_name='Trigo Rosario ($/Tn)')),
                ('rosario_girasol', models.DecimalField(decimal_places=2, default=350000.0, max_digits=12, verbose_name='Girasol Rosario ($/Tn)')),
                ('chicago_soja', models.DecimalField(decimal_places=2, default=382.5, max_digits=10, verbose_name='Soja Chicago (USD/Tn)')),
                ('chicago_maiz', models.DecimalField(decimal_places=2, default=176.4, max_digits=10, verbose_name='Maíz Chicago (USD/Tn)')),
                ('chicago_trigo', models.DecimalField(decimal_places=2, default=215.0, max_digits=10, verbose_name='Trigo Chicago (USD/Tn)')),
                ('chicago_girasol', models.DecimalField(decimal_places=2, default=310.0, max_digits=10, verbose_name='Girasol Chicago (USD/Tn)')),
            ],
            options={
                'verbose_name': 'Cotización de Mercado',
                'verbose_name_plural': 'Cotizaciones de Mercado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Identificador')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Municipio')),
                ('cabecera', models.CharField(max_length=100, verbose_name='Cabecera')),
                ('sheet_id', models.CharField(blank=True, max_length=150, verbose_name='ID de Google Sheets')),
                ('icono', models.CharField(default='🌾', max_length=10, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Entrega/Pago')),
                ('remito', models.CharField(blank=True, max_length=50, verbose_name='N° Remito')),
                ('kg_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Kg Netos')),
                ('chofer', models.CharField(blank=True, max_length=100, verbose_name='Chofer')),
                ('camion', models.CharField(blank=True, max_length=50, verbose_name='Patente Camión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_agro.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Movimiento / Entrega',
                'verbose_name_plural': 'Movimientos y Entregas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_agro.municipio', verbose_name='Municipio'),
        ),
    ]
